spring:
#  sleuth:
#    sampler:
#      #percentage: 1
#      probability: 1
  application:
    name: cloudpay-web
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    sender:
#      type: kafka  #配置zipkin发送类型为kafka
##    kafka:
##     topic: zipkin #kafka主题，不配置时默认使用zipkin
##    service:
##    设置服务名,不设置默认使用spring.application.name
##     name: gateway
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092 #集群的情况直接用“,”分割

server:
  port: 8081
  tomcat:
    max-connections: 1000
    max-threads: 300

management:
  server:
    port: 7071
#  security:
#    enabled: false # 默认值是 true, 为true的话那么页面上可能会报没有权限访问
# 开放所有Web 管理 Endpoints
  endpoints:
     web:
       exposure:
         include: \*


zuul:
  routes:
    #标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    cloudpay-core:
      #服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
      #这里zuul是自动依赖hystrix，ribbon的，不是面向单机
      path: /cloudpay-core/**
