spring:
  sleuth:
    sampler:
      #percentage: 1
      probability: 1
  application:
    name: cloudpay-web
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: kafka  #配置zipkin发送类型为kafka
#    kafka:
#     topic: zipkin #kafka主题，不配置时默认使用zipkin
#    service:
#    设置服务名,不设置默认使用spring.application.name
#     name: gateway
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #集群的情况直接用“,”分割

server:
  port: 8081
  tomcat:
    max-connections: 1000
    max-threads: 300

management:
  server:
    port: 7071

# 开放 所有Web 管理 Endpoints
  endpoints:
     web:
       exposure:
         include: \*

