debug: false

spring:
  application:
      name: cloudpay-db

  tomcat:
     accept-count: 400

  datasource:
     driver-class-name: com.mysql.jdbc.Driver

#     url: jdbc:mysql://127.0.0.1:8066/db_store?useUnicode=true&amp;characterEncoding=UTF-8
     url: jdbc:mysql://localhost:3306/db_store?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=15000&allowMultiQueries=true&useSSL=false
     username: root
     password: 123456
     # Hikari will use the above plus the following to setup connection pooling
     type: com.zaxxer.hikari.HikariDataSource
     hikari.minimum-idle: 50
     hikari.maximum-pool-size: 300
     hikari.auto-commit: true
     hikari.idle-timeout: 30000
     hikari.pool-name: ExpendHikariCP
     hikari.max-lifetime: 1800000
     hikari.connection-timeout: 30000
     hikari.connection-test-query: SELECT 1
#     default-auto-commit: true
#    #指定updates是否自动提交
#     auto-commit: true
#     maximum-pool-size: 100
#     max-idle: 10
#     max-wait: 10000
#     min-idle: 5
#     initial-size: 5
#     validation-query: SELECT 1
#     test-on-borrow: false
#     test-while-idle: true
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#     time-between-eviction-runs-millis: 18800
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#     minEvictableIdleTimeMillis: 300000
mybatis:
#     config-location: classpath:mybatis.cfg.xml    # mybatis配置文件所在路径
   mapper-locations: classpath:mappers/**.xml                              # 所有的mapper映射文件
